FROM node:18

WORKDIR /app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install

COPY backend/package*.json ./backend/
RUN cd backend && npm install

COPY frontend/ ./frontend/
RUN cd frontend && npm run build

COPY backend/ ./backend/
RUN cd backend && npm run build

WORKDIR /app/backend

EXPOSE 8080

CMD ["node", "index.js"]
